apiVersion: v1
kind: Secret
metadata:
  name: haproxy-config
type: Opaque
stringData:
  userData: |-
    #cloud-config
    write_files:
      - path: /tmp/haproxy.conf
        permissions: '0755'
        content: |
          #!/bin/bash