apiVersion: v1
kind: Secret
metadata:
  name: haproxy-config
type: Opaque
stringData:
  userData: |-
    #cloud-config
    write_files:
      - path: /etc/haproxy/haproxy.cfg
        permissions: '0755'
        content: |
          #---------------------------------------------------------------------
          # Global settings
          #---------------------------------------------------------------------
          global
              # to have these messages end up in /var/log/haproxy.log you will
    
              log         /dev/log local0
              chroot      /var/lib/haproxy
              pidfile     /var/run/haproxy.pid
              maxconn     4000
              user        haproxy
              group       haproxy
              daemon

              # turn on stats unix socket
              stats socket /var/lib/haproxy/stats

              # utilize system-wide crypto-policies
              ssl-default-bind-ciphers PROFILE=SYSTEM
              ssl-default-server-ciphers PROFILE=SYSTEM

          #---------------------------------------------------------------------
          # common defaults that all the 'listen' and 'backend' sections will
          # use if not designated in their block
          #---------------------------------------------------------------------
          defaults
              mode                    http
              log                     global
              option                  httplog
              option                  dontlognull
              option http-server-close
              option forwardfor       except 127.0.0.0/8
              option                  redispatch
              retries                 3
              timeout http-request    10s
              timeout queue           1m
              timeout connect         10s
              timeout client          1m
              timeout server          1m
              timeout http-keep-alive 10s
              timeout check           10s
              maxconn                 3000

          #---------------------------------------------------------------------
          # main frontend which proxys to the backends
          #---------------------------------------------------------------------
          frontend main
              bind *:8080
              default_backend             app

          #---------------------------------------------------------------------
          # round robin balancing between the various backends
          #---------------------------------------------------------------------
          backend app
              balance     roundrobin
              server  rosa 127.0.0.1:8080 check
              server  aro  127.0.0.1:8080 check
              server  osd  127.0.0.1:8080 check
