apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: fedora42-mysql-wp
    os.template.kubevirt.io/fedora: "true"
  name: fedora42-mysql-wp
  namespace: my-wordpress
spec:
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: fedora42-mysql-wp
        kubevirt.io/size: small
        expose: fedora42-mysql-wp
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            bios: {}
        machine:
          type: q35
        memory:
          guest: 2Gi
        resources: {}
      hostname: fedora42-mysql-wp
      networks:
      - name: default
        pod: {}
      nodeSelector:
        app: virtualmachine
      terminationGracePeriodSeconds: 180
      volumes:
      - containerDisk:
          image: quay.io/vhernandomartin/fedora-mysql-wp:v1.7
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            runcmd:
              - [sh, "/usr/local/bin/mysql_initial_startup.sh"]
        name: cloudinitdisk