apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-config
type: Opaque
stringData:
  userData: |-
    #cloud-config
    write_files:
      - path: /usr/local/bin/configure-wordpress.sh
        permissions: '0755'
        content: |
          #!/bin/bash

          WP_CONFIG="/var/www/html/wordpress/wp-config.php"

          # Read from mounted secret
          DB_NAME=wp # notsecret
          DB_USER="" # notsecret
          DB_PASSWORD="" # notsecret
          DB_HOST="" # notsecret

          # Update wp-config.php
          sed -i "s/define( 'DB_NAME', '.*' );/define( 'DB_NAME', '$DB_NAME' );/" $WP_CONFIG # notsecret
          sed -i "s/define( 'DB_USER', '.*' );/define( 'DB_USER', '$DB_USER' );/" $WP_CONFIG # notsecret
          sed -i "s/define( 'DB_PASSWORD', '.*' );/define( 'DB_PASSWORD', '$DB_PASSWORD' );/" $WP_CONFIG # notsecret
          sed -i "s/define( 'DB_HOST', '.*' );/define( 'DB_HOST', '$DB_HOST' );/" $WP_CONFIG # notsecret
    runcmd:
      - /usr/local/bin/configure-wordpress.sh
      - [sh, -xc, "sed -i 's/localhost/my-wp.victorhernando.es/' /etc/nginx/conf.d/wordpress-nginx.conf"]