apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: fedora42-nginx-wp
    os.template.kubevirt.io/fedora: "true"
  name: fedora42-nginx-wp
spec:
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: fedora42-nginx-wp
        kubevirt.io/size: small
        expose: fedora42-nginx-wp
    spec:
      accessCredentials:
      - secretRef:
          name: wordpress-db-config
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            bios: {}
        machine:
          type: q35
        memory:
          guest: 2Gi
        resources: {}
      hostname: fedora42-nginx-wp
      networks:
      - name: default
        pod: {}
      nodeSelector:
        app: virtualmachine
      terminationGracePeriodSeconds: 180
      volumes:
      - containerDisk:
          image: quay.io/vhernandomartin/fedora-nginx-wp:v1.5
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            write_files:
            - path: /usr/local/bin/configure-wordpress.sh
                permissions: '0755'
                content: |
                  #!/bin/bash

                  WP_CONFIG="/var/www/html/wordpress/wp-config.php"

                  # Read from mounted secret
                  DB_NAME=$(cat /var/run/kubevirt-private/access-credentials/wordpress-db-config/DB_NAME)
                  DB_USER=$(cat /var/run/kubevirt-private/access-credentials/wordpress-db-config/DB_USER)
                  DB_PASSWORD=$(cat /var/run/kubevirt-private/access-credentials/wordpress-db-config/DB_PASSWORD)
                  DB_HOST=$(cat /var/run/kubevirt-private/access-credentials/wordpress-db-config/DB_HOST)

                  # Update wp-config.php
                  sed -i "s/define( 'DB_NAME', '.*' );/define( 'DB_NAME', '$DB_NAME' );/" $WP_CONFIG
                  sed -i "s/define( 'DB_USER', '.*' );/define( 'DB_USER', '$DB_USER' );/" $WP_CONFIG
                  sed -i "s/define( 'DB_PASSWORD', '.*' );/define( 'DB_PASSWORD', '$DB_PASSWORD' );/" $WP_CONFIG
                  sed -i "s/define( 'DB_HOST', '.*' );/define( 'DB_HOST', '$DB_HOST' );/" $WP_CONFIG
            runcmd:
              - /usr/local/bin/configure-wordpress.sh
              - [sh, -xc, "sed -i 's/localhost/my-wp.victorhernando.es/' /etc/nginx/conf.d/wordpress-nginx.conf"]
        name: cloudinitdisk