apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: fedora42-httpd-multicloud
  labels:
    template.kubevirt.io/type: vm
    os.template.kubevirt.io/fedora: 'true'
    workload.template.kubevirt.io/server: 'true'
  annotations:
    name.os.template.kubevirt.io/fedora: Fedora
    description: Fedora 42 httpd multi-cloud template
    openshift.io/display-name: Fedora httpd multi-cloud VM
    iconClass: icon-fedora
  namespace: default
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      name: '${NAME}'
      annotations:
        description: Fedora 42 httpd multi-cloud
      labels:
        app: '${NAME}'
        vm.kubevirt.io/template: fedora42-httpd-multicloud
        os.template.kubevirt.io/fedora: 'true'
    spec:
      running: false
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: small
            vm.kubevirt.io/os: fedora
            vm.kubevirt.io/workload: server
          labels:
            kubevirt.io/domain: '${NAME}'
            kubevirt.io/size: small
        spec:
          domain:
            cpu:
              cores: 1
              sockets: 1
              threads: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: rootdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
              networkInterfaceMultiqueue: true
              rng: {}
            features:
              acpi: {}
              smm:
                enabled: true
            firmware:
              bootloader:
                efi: {}
            machine:
              type: q35
            memory:
              guest: 2Gi
          hostname: '${NAME}'
          networks:
            - name: default
              pod: {}
          terminationGracePeriodSeconds: 180
          volumes:
            - name: rootdisk
              containerDisk:
                image: quay.io/vhernandomartin/fedora-httpd-multicloud:v1.0 
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  users: fedora
                  password: '${CLOUD_USER_PASSWORD}'
                  chpasswd: { expire: False }
                  runcmd:
                    - [sh, -xc, "echo $(host $(dig +short myip.opendns.com @resolver1.opendns.com)|awk '{print $5}')"]
              name: cloudinitdisk
parameters:
  - name: NAME
    description: Name for the new VM
    generate: expression
    from: 'fedora42-httpd-multicloud-[a-z0-9]{16}'
  - name: CLOUD_USER_PASSWORD
    description: Randomized password for the cloud-init user
    generate: expression
    from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'