apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: install-kubevirt-hyperconverged
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: install-kubevirt-hyperconverged-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: install-kubevirt-hyperconverged-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: openshift-cnv
        server: "{{server}}"
      project: default
      sources:
        - path: configs/hyperconverged
          repoURL: https://github.com/vhernandomartin/openshift-virt-demo.git
          targetRevision: main
          repositoryType: git
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=false
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: install-kubevirt-hyperconverged-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - my-multicloud-env
  numberOfClusters: 2
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: NotIn
              values:
                - local-cluster

